Repository strinking/futaba, pull requests merged in 2018-10, with the labels that each got.

#97 Fix !about command
  futaba/cogs/misc/core.py
Labels: bug

#98 Add nickname command
  futaba/cogs/moderation/core.py
Labels: moderation

#100 Update profile pic
  images/futaba-portrait.png
Labels: enhancement

#102 Fixes for various runtime errors
  futaba/client.py
  futaba/cogs/info/core.py
  futaba/cogs/settings/core.py
  futaba/converters/role.py
  futaba/converters/user.py
  futaba/utils.py
Labels: bug

#142 Don't send channel.mention in DMs
  futaba/cogs/misc/core.py
Labels: bug

#143 Consistent role footer index
  futaba/cogs/info/core.py
Labels: enhancement

#141 Upload all unexpected tracebacks to an error channel
  futaba/client.py
  futaba/cogs/info/alias.py
  futaba/config.py
  futaba/str_builder.py
  misc/config.toml
Labels: enhancement

#144 Refactor check.py
  futaba/cogs/filter/check.py
  futaba/cogs/filter/check/__init__.py
  futaba/cogs/filter/check/common.py
  futaba/cogs/filter/check/file.py
  futaba/cogs/filter/check/name.py
  futaba/cogs/filter/check/text.py
Labels: enhancement

#150 Fix member join/leave duplicate events
  futaba/cogs/tracker/core.py
Labels: bug

#152 Add filter cause to journal output
  futaba/cogs/filter/check/common.py
  futaba/cogs/filter/check/file.py
  futaba/cogs/filter/check/name.py
  futaba/cogs/filter/check/text.py
Labels: enhancement, moderation

#151 Full message content
  JOURNAL_PATHS.md
  futaba/cogs/tracker/core.py
Labels: enhancement, moderation

#153 Sort output of journals by path
  futaba/sql/models/journal.py
Labels: enhancement

#158 Add configuration for HoundCI
  .flake8.ini
  .hound.yml
  futaba/cogs/info/core.py
  futaba/cogs/settings/core.py
  futaba/unicode.py
Labels: enhancement, question

#161 Allow filtering journal channels
  futaba/cogs/journal/core.py
  futaba/sql/models/journal.py
Labels: enhancement

#163 Add cleanup to message ID command
  JOURNAL_PATHS.md
  futaba/cogs/moderation/cleanup.py
Labels: feature, moderation

#164 Add missing f-string
  futaba/cogs/info/core.py
Labels: bug

#165 Add command to move log outputs between channels
  JOURNAL_PATHS.md
  futaba/cogs/journal/core.py
Labels: enhancement

#166 Remove setup comments
  futaba/cogs/_init.py
  futaba/cogs/filter/__init__.py
  futaba/cogs/info/__init__.py
  futaba/cogs/journal/__init__.py
  futaba/cogs/misc/__init__.py
  futaba/cogs/moderation/__init__.py
  futaba/cogs/navi/__init__.py
  futaba/cogs/reloader/__init__.py
  futaba/cogs/roles/__init__.py
  futaba/cogs/settings/__init__.py
  futaba/cogs/tracker/__init__.py
  futaba/cogs/welcome/__init__.py
Labels: enhancement

#167 Add jump links to filter events
  JOURNAL_PATHS.md
  futaba/cogs/filter/check/common.py
Labels: enhancement, moderation

#171 Change call to old SQL method
  futaba/cogs/journal/core.py
Labels: bug

#172 Add shellcheck to Hound
  .hound.yml
Labels: enhancement

#175 Catch and handle aiohttp network exceptions
  CONTRIBUTING.md
  JOURNAL_PATHS.md
  futaba/client.py
  futaba/cogs/misc/__init__.py
  futaba/cogs/misc/core.py
  futaba/cogs/misc/debug.py
  futaba/enums.py
Labels: enhancement

#176 Add warning of staff using mod actions manually
  futaba/cogs/moderation/__init__.py
  futaba/cogs/moderation/manual_mod_action_warn.py
  futaba/cogs/settings/core.py
  futaba/cogs/tracker/__init__.py
  futaba/cogs/tracker/core.py
  futaba/enums.py
  futaba/sql/models/settings.py
Labels: feature, moderation

#187 Requiring passing a jail duration
  futaba/cogs/moderation/core.py
Labels: small fix
