Repository strinking/futaba, pull requests merged in 2019-02, with the labels that each got.

#254 Add prune (purge command)
  JOURNAL_PATHS.md
  futaba/cogs/welcome/__init__.py
  futaba/cogs/welcome/prune.py
  futaba/emojis.py
Labels: feature

#268 Member ingest startup
  futaba/cogs/welcome/role_reapplication.py
Labels: enhancement

#258 Add !avatar command
  futaba/cogs/info/core.py
Labels: enhancement

#262 Fix role bypass on join
  futaba/cogs/moderation/core.py
  futaba/cogs/welcome/core.py
  futaba/cogs/welcome/role_reapplication.py
Labels: bug

#263 Pretty-print deleted-messages.json
  futaba/cogs/moderation/cleanup.py
Labels: enhancement

#266 Don't run welcome stuff on new bots
  futaba/cogs/welcome/core.py
Labels: small fix

#269 Change debug log message
  futaba/cogs/filter/check/__init__.py
Labels: small fix
