Repository strinking/futaba, pull requests merged in 2020-04, with the labels that each got.

#331 Update moderation SQL model
  futaba/sql/models/moderation.py
Labels: small fix

#332 Add separate commands for deletion-days ban, timed jail, unjail
  futaba/cogs/auth/core.py
  futaba/cogs/moderation/core.py
Labels: enhancement

#336 Refuse to cleanupid when passed a user ID
  futaba/cogs/moderation/cleanup.py
Labels: enhancement

#337 Fix jwt command bug
  futaba/cogs/auth/core.py
Labels: bug

#338 Use get_emoji to fetch emoj info
  futaba/cogs/info/core.py
  futaba/converters/emoji.py
Labels: enhancement
