Repository strinking/futaba, pull requests merged in 2020-05, with the labels that each got.

#344 Add selfjail command
  futaba/cogs/moderation/core.py
Labels: feature

#346 Don't fail on !help if a member disables DMs
  futaba/__init__.py
  futaba/client.py
  futaba/cogs/moderation/core.py
  futaba/help.py
Labels: bug, enhancement

#347 Address pylint and fix build
  futaba/client.py
  futaba/cogs/filter/manage.py
  futaba/cogs/journal/core.py
  futaba/cogs/settings/core.py
  futaba/enums.py
Labels: enhancement

#349 Exclude unremovable roles like nitro booster from jail "remove other roles" feature
  futaba/sql/models/moderation.py
Labels: bug
